export const INCREMENT_COUNT = 'INCREMENT_COUNT'
export const GET_TWEET_PAGE = 'GET_TWEET_PAGE'
export const INCREMENT_PAGE_COUNTER = 'INCREMENT_PAGE_COUNTER'
export const APPEND_TWEETS_PAGE = 'APPEND_TWEETS_PAGE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'

